{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: lilg-app-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "lilg.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecrets.clusterSecretStore }}
    kind: ClusterSecretStore
  target:
    name: lilg-app-secrets
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: {{ .Values.externalSecrets.appSecretKey }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: lilg-saml-keys
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "lilg.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecrets.clusterSecretStore }}
    kind: ClusterSecretStore
  target:
    name: lilg-saml-keys
    creationPolicy: Owner
  data:
    - secretKey: SAML_IDP_PRIVATE_KEY_PEM
      remoteRef:
        key: {{ .Values.externalSecrets.samlSecretKey }}
        property: privateKeyPem
    - secretKey: SAML_IDP_CERT_PEM
      remoteRef:
        key: {{ .Values.externalSecrets.samlSecretKey }}
        property: certPem
{{- end }}
