apiVersion: v1
kind: Service
metadata:
  name: lilg-api
  namespace: {{ .Release.Namespace }}
  labels:
    app: lilg-api
    {{- include "lilg.labels" . | nindent 4 }}
spec:
  selector:
    app: lilg-api
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
